"""initial schema

Revision ID: 9c389dc2e34b
Revises:
Create Date: 2026-08-15 18:24:14.838972

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apple_health_metric_catalog",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("record_type", sa.String(length=200), nullable=False),
        sa.Column("friendly_name", sa.String(length=200), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approx_record_count", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("sophie_use", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apple_health_metric_catalog_record_type"),
        "apple_health_metric_catalog",
        ["record_type"],
        unique=False,
    )
    op.create_table(
        "body_composition_assessment",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("assessed_at", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("body_fat_pct", sa.Float(), nullable=True),
        sa.Column("lean_mass_kg", sa.Float(), nullable=True),
        sa.Column("segmental_json", sa.JSON(), nullable=True),
        sa.Column("visceral_metric", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_body_composition_assessment_assessed_at"),
        "body_composition_assessment",
        ["assessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_body_composition_assessment_profile_id"),
        "body_composition_assessment",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "calendar_snapshot",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("busy_intervals", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calendar_snapshot_profile_id"), "calendar_snapshot", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_calendar_snapshot_week_start"), "calendar_snapshot", ["week_start"], unique=False
    )
    op.create_table(
        "canonical_workout",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("avg_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column("elevation_gain_m", sa.Float(), nullable=True),
        sa.Column("avg_pace_s_per_km", sa.Float(), nullable=True),
        sa.Column("source_quality", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_workout_profile_id"), "canonical_workout", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_canonical_workout_start_at"), "canonical_workout", ["start_at"], unique=False
    )
    op.create_table(
        "circadian_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("bedtime_variability_min", sa.Float(), nullable=True),
        sa.Column("waketime_variability_min", sa.Float(), nullable=True),
        sa.Column("sleep_midpoint_local", sa.String(length=5), nullable=True),
        sa.Column("duration_consistency", sa.Float(), nullable=True),
        sa.Column("disrupted_nights", sa.Integer(), nullable=False),
        sa.Column("avg_daylight_minutes", sa.Float(), nullable=True),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_circadian_summary_profile_id"), "circadian_summary", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_circadian_summary_week_start"), "circadian_summary", ["week_start"], unique=False
    )
    op.create_table(
        "clinical_symptom_note",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("entered_at", sa.Date(), nullable=False),
        sa.Column("symptom", sa.String(length=200), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_symptom_note_profile_id"),
        "clinical_symptom_note",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "daily_health_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("walking_running_distance_m", sa.Float(), nullable=True),
        sa.Column("active_energy_kcal", sa.Float(), nullable=True),
        sa.Column("exercise_minutes", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.Float(), nullable=True),
        sa.Column("hrv_ms", sa.Float(), nullable=True),
        sa.Column("sleep_minutes", sa.Float(), nullable=True),
        sa.Column("sleep_efficiency", sa.Float(), nullable=True),
        sa.Column("bedtime_local", sa.String(length=5), nullable=True),
        sa.Column("waketime_local", sa.String(length=5), nullable=True),
        sa.Column("respiratory_rate", sa.Float(), nullable=True),
        sa.Column("spo2_pct", sa.Float(), nullable=True),
        sa.Column("wrist_temp_deviation_c", sa.Float(), nullable=True),
        sa.Column("vo2_max", sa.Float(), nullable=True),
        sa.Column("daylight_minutes", sa.Float(), nullable=True),
        sa.Column("dietary_energy_kcal", sa.Float(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("carbs_g", sa.Float(), nullable=True),
        sa.Column("fat_g", sa.Float(), nullable=True),
        sa.Column("mindful_minutes", sa.Float(), nullable=True),
        sa.Column("headphone_audio_db", sa.Float(), nullable=True),
        sa.Column("environmental_audio_db", sa.Float(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_health_summary_day"), "daily_health_summary", ["day"], unique=False
    )
    op.create_index(
        op.f("ix_daily_health_summary_profile_id"),
        "daily_health_summary",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "family_history_item",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hearing_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("headphone_avg_db", sa.Float(), nullable=True),
        sa.Column("environmental_avg_db", sa.Float(), nullable=True),
        sa.Column("exposure_events", sa.Integer(), nullable=False),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hearing_summary_profile_id"), "hearing_summary", ["profile_id"], unique=False
    )
    op.create_table(
        "import_manifest",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("importer_version", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("duplicates_detected", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error_summary", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_manifest_content_fingerprint"),
        "import_manifest",
        ["content_fingerprint"],
        unique=False,
    )
    op.create_table(
        "manual_checkin",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("pain_0_10", sa.Integer(), nullable=True),
        sa.Column("pain_location", sa.String(length=100), nullable=True),
        sa.Column("stress_1_5", sa.Integer(), nullable=True),
        sa.Column("fasting_quality", sa.String(length=10), nullable=True),
        sa.Column("nutrition_quality", sa.String(length=10), nullable=True),
        sa.Column("alcohol", sa.String(length=10), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manual_checkin_profile_id"), "manual_checkin", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_manual_checkin_week_start"), "manual_checkin", ["week_start"], unique=False
    )
    op.create_table(
        "movement_baseline",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("avg_daily_steps", sa.Float(), nullable=True),
        sa.Column("personal_baseline_steps", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movement_baseline_profile_id"), "movement_baseline", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_movement_baseline_week_start"), "movement_baseline", ["week_start"], unique=False
    )
    op.create_table(
        "plan",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("conservative_alternative", sa.JSON(), nullable=True),
        sa.Column("coach_note", sa.String(), nullable=True),
        sa.Column("llm_used", sa.Boolean(), nullable=False),
        sa.Column("validation_notes", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_profile_id"), "plan", ["profile_id"], unique=False)
    op.create_index(op.f("ix_plan_week_start"), "plan", ["week_start"], unique=False)
    op.create_table(
        "recovery_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recovery_summary_day"), "recovery_summary", ["day"], unique=False)
    op.create_index(
        op.f("ix_recovery_summary_profile_id"), "recovery_summary", ["profile_id"], unique=False
    )
    op.create_table(
        "training_load_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("load_ratio", sa.Float(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("data_quality", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_load_summary_profile_id"),
        "training_load_summary",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_load_summary_week_start"),
        "training_load_summary",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "user_config",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_weight_kg", sa.Float(), nullable=True),
        sa.Column("weight_goal_kg", sa.Float(), nullable=True),
        sa.Column("race_name", sa.String(length=200), nullable=True),
        sa.Column("race_date", sa.Date(), nullable=True),
        sa.Column("other_goals", sa.JSON(), nullable=False),
        sa.Column("max_runs_per_week", sa.Integer(), nullable=False),
        sa.Column("padel_weekday", sa.Integer(), nullable=True),
        sa.Column("dropoff_start", sa.String(length=5), nullable=False),
        sa.Column("dropoff_end", sa.String(length=5), nullable=False),
        sa.Column("earliest_weekday_session", sa.String(length=5), nullable=False),
        sa.Column("latest_session", sa.String(length=5), nullable=False),
        sa.Column("long_run_weekday_preference", sa.JSON(), nullable=False),
        sa.Column("preserve_rest_day", sa.Boolean(), nullable=False),
        sa.Column("gluten_free", sa.Boolean(), nullable=False),
        sa.Column("paleo_inspired", sa.Boolean(), nullable=False),
        sa.Column("fasting_window", sa.String(length=20), nullable=True),
        sa.Column("weather_location_name", sa.String(length=200), nullable=True),
        sa.Column("weather_lat", sa.Float(), nullable=True),
        sa.Column("weather_lon", sa.Float(), nullable=True),
        sa.Column("active_block_name", sa.String(length=200), nullable=True),
        sa.Column("explicit_exclusions", sa.JSON(), nullable=False),
        sa.Column("sophie_memory", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id"),
    )
    op.create_table(
        "weather_snapshot",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("for_date", sa.Date(), nullable=False),
        sa.Column("location_name", sa.String(length=200), nullable=True),
        sa.Column("lat_rounded", sa.Float(), nullable=True),
        sa.Column("lon_rounded", sa.Float(), nullable=True),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("humidity_pct", sa.Float(), nullable=True),
        sa.Column("precip_mm", sa.Float(), nullable=True),
        sa.Column("wind_kph", sa.Float(), nullable=True),
        sa.Column("condition_summary", sa.String(length=100), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weather_snapshot_for_date"), "weather_snapshot", ["for_date"], unique=False
    )
    op.create_index(
        op.f("ix_weather_snapshot_profile_id"), "weather_snapshot", ["profile_id"], unique=False
    )
    op.create_table(
        "weekly_summary",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("planned_running_distance_m", sa.Float(), nullable=True),
        sa.Column("actual_running_distance_m", sa.Float(), nullable=True),
        sa.Column("planned_session_count", sa.Integer(), nullable=True),
        sa.Column("actual_session_count", sa.Integer(), nullable=True),
        sa.Column("long_run_distance_m", sa.Float(), nullable=True),
        sa.Column("other_training_minutes", sa.Float(), nullable=True),
        sa.Column("avg_weight_kg", sa.Float(), nullable=True),
        sa.Column("avg_resting_hr", sa.Float(), nullable=True),
        sa.Column("avg_hrv_ms", sa.Float(), nullable=True),
        sa.Column("avg_sleep_minutes", sa.Float(), nullable=True),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weekly_summary_profile_id"), "weekly_summary", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_weekly_summary_week_start"), "weekly_summary", ["week_start"], unique=False
    )
    op.create_table(
        "wellbeing_assessment",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument", sa.String(length=20), nullable=False),
        sa.Column("instrument_version", sa.String(length=20), nullable=False),
        sa.Column("raw_score", sa.Integer(), nullable=False),
        sa.Column("percentage_score", sa.Integer(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wellbeing_assessment_assessed_at"),
        "wellbeing_assessment",
        ["assessed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wellbeing_assessment_profile_id"),
        "wellbeing_assessment",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "aerobic_efficiency_point",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("workout_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("pace_s_per_km", sa.Float(), nullable=False),
        sa.Column("avg_hr", sa.Float(), nullable=False),
        sa.Column("efficiency_proxy", sa.Float(), nullable=False),
        sa.Column("comparable_group", sa.String(length=20), nullable=False),
        sa.Column("calculation_version", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["canonical_workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aerobic_efficiency_point_profile_id"),
        "aerobic_efficiency_point",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_aerobic_efficiency_point_week_start"),
        "aerobic_efficiency_point",
        ["week_start"],
        unique=False,
    )
    op.create_table(
        "clinical_import",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("import_manifest_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_manifest_id"],
            ["import_manifest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinical_import_profile_id"), "clinical_import", ["profile_id"], unique=False
    )
    op.create_table(
        "decision_log",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=True),
        sa.Column("recommended_plan_ref", sa.String(), nullable=True),
        sa.Column("approved_plan_ref", sa.String(), nullable=True),
        sa.Column("actual_result_summary", sa.String(), nullable=True),
        sa.Column("training_load_status", sa.String(length=20), nullable=True),
        sa.Column("data_quality_summary", sa.String(), nullable=True),
        sa.Column("coach_note", sa.String(), nullable=True),
        sa.Column("calendar_write_state", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_plan_ref"],
            ["plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommended_plan_ref"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_log_profile_id"), "decision_log", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_decision_log_week_start"), "decision_log", ["week_start"], unique=False
    )
    op.create_table(
        "session",
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=True),
        sa.Column("session_type", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=200), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("estimated_duration_min", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("calendar_event_id", sa.String(length=200), nullable=True),
        sa.Column("matched_workout_id", sa.String(), nullable=True),
        sa.Column("completion_status", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_workout_id"],
            ["canonical_workout.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_plan_id"), "session", ["plan_id"], unique=False)
    op.create_table(
        "workout_source_provenance",
        sa.Column("canonical_workout_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_identifier", sa.String(length=200), nullable=True),
        sa.Column("raw_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_duration_s", sa.Integer(), nullable=True),
        sa.Column("raw_distance_m", sa.Float(), nullable=True),
        sa.Column("matched_confidence", sa.String(length=20), nullable=False),
        sa.Column("import_manifest_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_workout_id"],
            ["canonical_workout.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_manifest_id"],
            ["import_manifest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_source_provenance_canonical_workout_id"),
        "workout_source_provenance",
        ["canonical_workout_id"],
        unique=False,
    )
    op.create_table(
        "lab_result",
        sa.Column("profile_id", sa.String(), nullable=False),
        sa.Column("clinical_import_id", sa.String(), nullable=False),
        sa.Column("sample_date", sa.Date(), nullable=False),
        sa.Column("test_name", sa.String(length=200), nullable=False),
        sa.Column("canonical_test_id", sa.String(length=100), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("value_text", sa.String(length=200), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("reference_low", sa.Float(), nullable=True),
        sa.Column("reference_high", sa.Float(), nullable=True),
        sa.Column("reference_text", sa.String(length=100), nullable=True),
        sa.Column("abnormal_flag", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["clinical_import_id"],
            ["clinical_import.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lab_result_canonical_test_id"), "lab_result", ["canonical_test_id"], unique=False
    )
    op.create_index(op.f("ix_lab_result_profile_id"), "lab_result", ["profile_id"], unique=False)
    op.create_index(op.f("ix_lab_result_sample_date"), "lab_result", ["sample_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lab_result_sample_date"), table_name="lab_result")
    op.drop_index(op.f("ix_lab_result_profile_id"), table_name="lab_result")
    op.drop_index(op.f("ix_lab_result_canonical_test_id"), table_name="lab_result")
    op.drop_table("lab_result")
    op.drop_index(
        op.f("ix_workout_source_provenance_canonical_workout_id"),
        table_name="workout_source_provenance",
    )
    op.drop_table("workout_source_provenance")
    op.drop_index(op.f("ix_session_plan_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_decision_log_week_start"), table_name="decision_log")
    op.drop_index(op.f("ix_decision_log_profile_id"), table_name="decision_log")
    op.drop_table("decision_log")
    op.drop_index(op.f("ix_clinical_import_profile_id"), table_name="clinical_import")
    op.drop_table("clinical_import")
    op.drop_index(
        op.f("ix_aerobic_efficiency_point_week_start"), table_name="aerobic_efficiency_point"
    )
    op.drop_index(
        op.f("ix_aerobic_efficiency_point_profile_id"), table_name="aerobic_efficiency_point"
    )
    op.drop_table("aerobic_efficiency_point")
    op.drop_index(op.f("ix_wellbeing_assessment_profile_id"), table_name="wellbeing_assessment")
    op.drop_index(op.f("ix_wellbeing_assessment_assessed_at"), table_name="wellbeing_assessment")
    op.drop_table("wellbeing_assessment")
    op.drop_index(op.f("ix_weekly_summary_week_start"), table_name="weekly_summary")
    op.drop_index(op.f("ix_weekly_summary_profile_id"), table_name="weekly_summary")
    op.drop_table("weekly_summary")
    op.drop_index(op.f("ix_weather_snapshot_profile_id"), table_name="weather_snapshot")
    op.drop_index(op.f("ix_weather_snapshot_for_date"), table_name="weather_snapshot")
    op.drop_table("weather_snapshot")
    op.drop_table("user_config")
    op.drop_index(op.f("ix_training_load_summary_week_start"), table_name="training_load_summary")
    op.drop_index(op.f("ix_training_load_summary_profile_id"), table_name="training_load_summary")
    op.drop_table("training_load_summary")
    op.drop_index(op.f("ix_recovery_summary_profile_id"), table_name="recovery_summary")
    op.drop_index(op.f("ix_recovery_summary_day"), table_name="recovery_summary")
    op.drop_table("recovery_summary")
    op.drop_index(op.f("ix_plan_week_start"), table_name="plan")
    op.drop_index(op.f("ix_plan_profile_id"), table_name="plan")
    op.drop_table("plan")
    op.drop_index(op.f("ix_movement_baseline_week_start"), table_name="movement_baseline")
    op.drop_index(op.f("ix_movement_baseline_profile_id"), table_name="movement_baseline")
    op.drop_table("movement_baseline")
    op.drop_index(op.f("ix_manual_checkin_week_start"), table_name="manual_checkin")
    op.drop_index(op.f("ix_manual_checkin_profile_id"), table_name="manual_checkin")
    op.drop_table("manual_checkin")
    op.drop_index(op.f("ix_import_manifest_content_fingerprint"), table_name="import_manifest")
    op.drop_table("import_manifest")
    op.drop_index(op.f("ix_hearing_summary_profile_id"), table_name="hearing_summary")
    op.drop_table("hearing_summary")
    op.drop_table("family_history_item")
    op.drop_index(op.f("ix_daily_health_summary_profile_id"), table_name="daily_health_summary")
    op.drop_index(op.f("ix_daily_health_summary_day"), table_name="daily_health_summary")
    op.drop_table("daily_health_summary")
    op.drop_index(op.f("ix_clinical_symptom_note_profile_id"), table_name="clinical_symptom_note")
    op.drop_table("clinical_symptom_note")
    op.drop_index(op.f("ix_circadian_summary_week_start"), table_name="circadian_summary")
    op.drop_index(op.f("ix_circadian_summary_profile_id"), table_name="circadian_summary")
    op.drop_table("circadian_summary")
    op.drop_index(op.f("ix_canonical_workout_start_at"), table_name="canonical_workout")
    op.drop_index(op.f("ix_canonical_workout_profile_id"), table_name="canonical_workout")
    op.drop_table("canonical_workout")
    op.drop_index(op.f("ix_calendar_snapshot_week_start"), table_name="calendar_snapshot")
    op.drop_index(op.f("ix_calendar_snapshot_profile_id"), table_name="calendar_snapshot")
    op.drop_table("calendar_snapshot")
    op.drop_index(
        op.f("ix_body_composition_assessment_profile_id"), table_name="body_composition_assessment"
    )
    op.drop_index(
        op.f("ix_body_composition_assessment_assessed_at"), table_name="body_composition_assessment"
    )
    op.drop_table("body_composition_assessment")
    op.drop_index(
        op.f("ix_apple_health_metric_catalog_record_type"), table_name="apple_health_metric_catalog"
    )
    op.drop_table("apple_health_metric_catalog")
    op.drop_table("profile")
    # ### end Alembic commands ###
